name: Simple Vue Deploy

on: push

jobs:
  deploy:
    runs-on: self-hosted
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 16
      - name: Building Production
        run: |
          npm i
          npm run build
